OjoRise/FrontEnd

src/app/page.tsx
=> OJORISE-13-remove-build-error-for-Frontend-deploy

package-lock.json, package.json, src/lib/axios.ts, src/services/kakaoLogin.ts
axios 인스턴스 및 kakaoLogin api 모듈을 구성하였습니다.
각자 .env 파일을 만들어서 파일 안에
NEXT_PUBLIC_SERVER_URL=http://localhost:8080/eureka/api
를 넣어주세요!
=> OJORISE-14-setup-axios

build.sh
=> OJORISE-11-deploy-auto-backend

.github/workflows/git-push.yml
=> OJORISE-10 FIX: git-push.yml 수정

src/utils/requestHelper.ts
Get 요청에 필요한 Query string 생성용 function 구현
=> OJORISE-25-add-build-queryString

src/app/globals.css
테블릿 이하 환경에서는 우측 스크롤바가 display hidden되도록 설정
=> OJORISE-27-Delete-side-scroll-bar

package-lock.json, package.json, src/app/api/chat/route.ts, src/app/chat/page.tsx
=> OJORISE-35-connect-AI

src/components/ChatBotBubble.tsx, src/components/ChatBotModal.tsx
=> OJORISE-37-add-chatbot-UI

src/components/page-component/BannerCarousel.tsx
OJORISE-59
배너의 이미지가 뜨지 않아 height값을 style 안에 넣었습니다.
이미지가 잘 뜨는지 확인 바랍니다.
=> OJORISE-59-fix-banner-img-code

src/components/common/chatbot/ChatBotBubble.tsx, src/components/common/chatbot/ChatBotModal.tsx, src/type/UserProfile.ts
=> OJORISE-74-fix-chatbot

src/components/page-component/main-page/plan/GuestPlanSelector.tsx, src/components/page-component/main-page/plan/GuestPrompt.tsx, src/components/page-component/main-page/plan/PlanInfoLoggedIn.tsx
PlanInfoLoggedIn 컴포넌트가 데스크탑 전용 레이아웃으로 고정되어 있어, 모바일 및 태블릿 환경에서 보기 어려운 문제가 있었습니다.
=> OJORISE-75-Banner-responsive

src/components/page-component/BannerCarousel.tsx
=> OJORISE-79-Banner-responsive

src/components/common/Footer.tsx, src/components/common/wrapper/ClientLayoutWrapper.tsx
푸터 만들었습니다.
나중에 회의를 통해 푸터에 들어갈 내용, 디자인 정하면 좋을 것 같습니다.
=> OJORISE-80-add-footer-section

src/components/common/AppHeader.tsx, src/hooks/useLogout.ts, src/services/auth.ts
로그아웃 기능 구현하였습니다.
로그아웃 후 토큰이 정상적으로 삭제되는지 확인 부탁드립니다.
=> OJORISE-88-feat-logout

src/hooks/useSurvey.ts, src/lib/axios.ts, src/services/ageTest.ts
=> OJORISE-111 remove axios error

src/components/page-component/main-page/compare-chart/RadarChart.tsx, src/components/page-component/main-page/compare-chart/comparePlan.ts
=> OJORISE-109-Fix-chart-issue

src/app/globals.css, src/components/common/chatbot/ChatBotBubble.tsx, src/components/common/chatbot/ChatBotModal.tsx, src/components/ui/scroll-area.tsx
스크롤바 제거
반응형에 맞춰 chatbotBubble 크기 수정
챗봇 알림창 demo 제작
=> OJORISE-124-fix-chatbot-ui

src/app/globals.css, src/app/layout.tsx, src/components/common/wrapper/ClientLayoutWrapper.tsx
=> OJORISE-125 modify the FAB

src/components/common/chatbot/ChatBotModal.tsx
=> OJORISE-130 add planList to sessionStorage

src/components/common/chatbot/ChatBotModal.tsx, src/services/ocr.ts
=> OJORISE-132 fix ocr api and chatbot modal

src/app/globals.css, src/components/common/survey/StepItem.tsx, src/components/page-component/edit-survey/EditSurveyPage.tsx, src/components/page-component/main-page/compare-plans/PlanCard.tsx, src/components/page-component/main-page/compare-plans/SelectedPlanViewer.tsx, src/components/page-component/mypage/MyPage.tsx, src/components/page-component/signup/SignupPage.tsx
Ojorise 127 fix components
요금제 비교 화면 UI 수정
=> Ojorise 127 fix components

src/components/page-component/main-page/compare-plans/RecommendedPlanList.tsx
게스트 모드에서 recommendPlans가 나오도록 수정
=> OJORISE-150 add recommendPlans

src/components/common/AppHeader.tsx, src/components/common/OffCanvas.tsx
모바일 환경에서의 메뉴명의 크기, 로고의 크기, 데스크톱환경에서의 메뉴 크기를 수정
=> OJORISE-149-FIX: fixed appheader style

src/components/page-component/main-page/compare-plans/PlanCard.tsx, src/types/plan.ts
=> OJORISE-157 add plancard URL

src/components/page-component/tongbti/result/ResultPage.tsx
OJORISE-164-fix-not-used-resultMap
typekeyMap 안 쓰는 것 삭제 
=> OJORISE-164 FIX: typekeyMap 안 쓰는 것 삭제

src/components/common/chatbot/ChatBotModal.tsx, src/components/page-component/main-page/compare-plans/RecommendedPlanList.tsx, src/components/page-component/test-age-page/result/AgeTestResult.tsx, src/components/page-component/tongbti/QuestionCard.tsx, src/hooks/useRecommendedPlans.ts, src/stores/usePlanStore.ts
=> OJORISE-167 fix the recommends

src/components/page-component/main-page/compare-plans/PlanCard.tsx, src/components/page-component/main-page/compare-plans/RecommendedPlanList.tsx
=> OJORISE-167 modify the remove functions

src/components/page-component/main-page/MainPage.tsx, src/components/page-component/main-page/compare-chart/RadarChart.tsx
=> OJORISE-170-fix-chart
